{{ if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tokenx.jwker.fullname" . }}-apiserver
  labels:
    {{- include "tokenx.jwker.labels" . | nindent 4 }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.apiServerCIDR | required ".Values.networkPolicy.apiServerCIDR is required." }}
  podSelector:
    matchLabels:
      {{- include "tokenx.jwker.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
{{ end }}
