---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "tokenx.jwker.labels" . | nindent 4 }}
  name: {{ include "tokenx.jwker.fullname" . }}
rules:
  - apiGroups:
      - nais.io
    resources:
      - jwkers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - get
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "tokenx.jwker.labels" . | nindent 4 }}
  name: {{ include "tokenx.jwker.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tokenx.jwker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tokenx.jwker.fullname" . }}
    namespace: "{{ .Release.Namespace }}"
