apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: jwker-env
  labels:
    {{- include "tokenx.jwker.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.jwker.secrets.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  TOKENDINGS_URL: "{{- include "tokenx.tokendings.URL" . }}"
