apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ .Values.secretName }}
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "tokenx.jwker.labels" . | nindent 4 }}
stringData:
  CLUSTER_NAME: {{ .Values.clusterName | required ".Values.clusterName is required." | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  JWKER_PRIVATE_JWK: {{ .Values.privateJwk | required ".Values.privateJwk is required." | quote }}
  JWKER_CLIENT_ID: "jwker"
  TOKENDINGS_INSTANCES: {{ join "," .Values.tokendings.instanceUrls | quote }}
  TOKENDINGS_URL: "{{- include "tokenx.tokendings.URL" . }}"
