@startuml component

participant cluster
participant jwker
participant naiserator
participant application
participant tokendings
participant anotherapplication
participant idprovider

==Jwker initialization==
jwker -> jwker: create jwk and sign claims in oAuth-form
jwker -> idprovider: fetch accessToken for token-dings

==Deploy application==
developer -> cluster: apply ´application´ resource
cluster <- naiserator: read application resource
cluster <- naiserator: create and apply jwker resource
note left: containing accessPolicies and unique secret name
cluster <- naiserator: create deployment spec referencing unique secret name
jwker -> cluster: read jwker resource
jwker -> cluster: get all jwker-created secrets for app
note left: get currently used secrets to register with tokendings
jwker -> jwker: Create jwks for application
jwker -> tokendings: POST app jwks and accessPolicies to /registration/client
note right: using accessToken from idProvider, jwks contains all currently used public keys
jwker -> cluster: write new secret
note left: secret name from jwker referenced in application deployment spec
cluster -> application: inject new secret
jwker -> cluster: delete unreferenced secrets

@enduml
