name: Build and deploy jwker

on: [push]

env:
  image: ghcr.io/${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Extract version of Go to use
        run: echo "GOVERSION=$(cat go.mod | grep -w "go" | awk ' { print $2 } ' | grep -w "^[^v]")" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Setup Test
        run: |
          make kubebuilder
      - name: Test Go
        run: |
          make test
  build:
    needs:
      - test
    name: Checkout code and setup node
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an push the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}
  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: jwker
    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
        app-id: ${{ secrets.NAIS_APP_ID }}
        repo: navikt/nais-yaml
    - name: Checkout nais-yaml
      uses: actions/checkout@v3
      with:
        repository: navikt/nais-yaml
        token: ${{ steps.get-token.outputs.token }}
        path: nais-yaml
    - name: Generate image environment variable
      run: |
        cd jwker
        version=$(./version.sh)
        echo "version=${version}" >> $GITHUB_ENV
        echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
    - name: Bump version in nais-yaml
      run: |
        cd nais-yaml
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        sed -E -i "s#image: ghcr.io/nais/jwker.+#image: ${IMAGE}#" vars/global.yaml
        git add .
        git --no-pager diff --cached
        git commit --no-verify -a -m "Bump jwker to version ${version}"
        git push
