name: Build and deploy jwker

on: [push]

env:
  image: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Checkout code and setup node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an push the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}
  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate image environment variable
      run: |
        version=$(./version.sh)
        echo "version=${version}" >> $GITHUB_ENV
        echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
        echo "NAIS_YAML=${GITHUB_WORKSPACE}/nais-yaml" >> $GITHUB_ENV
        pwd
    - name: Bump version in nais-yaml
      env:
        DEPLOY_KEY: ${{ secrets.NAIS_YAML_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        mkdir -p $NAIS_YAML
        git clone git@github.com:navikt/nais-yaml.git $NAIS_YAML
        cd $NAIS_YAML
        git config user.email "aura@nav.no"
        git config user.name "NAIS deploy pipeline"
        sed -E -i "s#image: .+#image: ${IMAGE}#" vars/jwker.yaml
        git add .
        git --no-pager diff --cached
        git commit -a -m "Bump jwker to version ${version}"
        git push
