name: Build and deploy jwker
on:
  push:
    paths-ignore:
      - 'README.md'
env:
  GOOGLE_REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
  GITHUB_REGISTRY: ghcr.io
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4 # ratchet:actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # ratchet:actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # ratchet:actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Test
        run: |
          make kubebuilder
      - name: Test Go
        run: |
          make test
  publish-images:
    needs: test
    name: Publish to Google and GitHub registries
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    env:
      RUNNER_IMG: "gcr.io/distroless/static-debian11:nonroot"
      BASEIMG_IDENTITY: "keyless@distroless.iam.gserviceaccount.com"
      BASEIMG_ISSUER: "https://accounts.google.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ratchet:actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@1fc5bd396d372bee37d608f955b336615edf79c8 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.1.1'
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/platform-build-push-sign@fb7da39ee56c8904ed15c02705a1780cb278a65b # ratchet:nais/platform-build-push-sign@main
        id: build_push_sign
        with:
          name: jwker
          dockerfile: Dockerfile
          google_service_account: gh-jwker
          push: true
          push_ghcr: true
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
